### PR TITLE
Fix Memory Card B

### PR DESCRIPTION
**Pull request by greyrogue**
Only IPL 1.0 Reading of memcard B was tested.

### CODE REVIEW

**Comment by greyrogue** [comment]
Changing the Config Bit for Memcard B on me, eh.  Fiendishly clever.

I changed the debug statements in EXI.c because the ctx was moved to a different file.  Feel free to change this however you'd like.

**Comment by GerbilSoft** [comment]
I think you may have missed some of my comments earlier. I cherry-picked your original commit into a rebased branch and pushed it as MemCard-hax.r431.v2 - you merged it into the original one, which had a minor rebase issue related to the config bit value.

I see there are a few other changes in the ASM files here, so if you create another PR with just those files for MemCard-hax.r431.v2, I'll merge them in.

(Among other things, IRQ_Cause[] is now an array, using the EXI channel number as the array index.)

**Comment by greyrogue** [comment]
I think I'm just cleaning up the fix (Sonics look to be working).  Where do you want it merged?

**Comment by GerbilSoft** [comment]
Use the MemCard-hax.r431.v2 branch.

**Pull request closed without merging**
