### PR TITLE
Memcard B reading in IPL 1.0

### PR DESCRIPTION
**Pull request by greyrogue**
Finished changes to get Memcard B working.  Only tested reading in IPL.
No other testing done.

### CODE REVIEW

**Comment by greyrogue** [comment]
I noticed when debugging that EXI debug messages are lost after IPL starts loading the disc.  I started running with a real disc and ejected the disc as soon as Nintendont had read the header to get around this.  Not certain of the cause.

**Comment by GerbilSoft** [comment]
Looking through your code, I guess it's the missing IRQ for EXI channel 1 that was preventing Slot B from working. I'll need to rebase MemCard-hax.r411 to the latest code first before merging and testing this PR though.

**Comment by greyrogue** [comment]
The whole EXI patching might need to be redone.  EXILock,EXIUnlock etc. are doing more than the patches do.  Not sure if this can cause issues.

**Comment by greyrogue** [comment]
Actually, the missing second SRAM checksum was causing problems before it even got to the other IRQ, but both changes were needed.  Those debugging lines I left in can be removed.

**Comment by GerbilSoft** [comment]
Rebasing might take a while. I'm leaving out GCI folders for now, since a prerequisite is moving card formatting to the kernel, which won't work right because the kernel doesn't have write caching.

**Comment by GerbilSoft** [comment]
Can you rebase this commit on MemCard-hax.r431? I rebased it to the latest master plus my recent ShowGameInfo loader changes. (Note that this branch doesn't have GCI folders.) (You may need to create a new branch, copy the diffs there, and submit another PR.)

EDIT: Can't seem to get MemCard-hax.r431 to recognize the second card even as broken yet. Need to figure out why it isn't being picked up before testing out this patch.

EDIT 2: Turns out I missed a configuration bit shift in the ASM code in the rebase. (Triforce Arcade Mode shifted over the "Slot B" configuration bit.) MemCard-hax.r431.v2 has everything "working" (well, Slot B is still broken right now). Will test this patch in a bit.

**Comment by GerbilSoft** [comment]
Okay I tested the patch and cherry-picked it into MemCard-hax.r431.v2. Here's my notes:
* IPL works great. Modifying and copying files works as expected.
* Sonic Adventure 2: Battle crashes after the Progressive Scan screen.
* Sonic Adventure DX works, but if you select Slot B, it crashes. (Slot A works fine.)

Still needs work before merging to mainline, but it's farther than I've managed to get by myself. :) If you manage to get more stuff done, open a PR with the new commits for the  MemCard-hax.r431.v2 branch.

**Pull request closed without merging**
